insert into socios(id,cedula,nombre,apellido,fecha_nac,num_celular,genero,email,lugar_nacimiento,personas_dependientes,profecion,direccion,provincia,ciudad,parroquia,sector,referencia,telefono,tipo_casa,tiempo_residencia,propietario) 
values (1,'0104050203','Carmen', 'Tacuri', '1974-01-04', '0959678423', 'F', 'tacurijuanita@hotmail.com', 'Cuneca', 'Si', 'Doctora', 'AV. España', 'Azuay', 'Cuenca', 'Monay', 'El Arenal', 'Feria Libre', '045678901', 'Propia', '10 años', 'Carmen Tacuri',);
insert into socios(id,cedula,nombre,apellido,fecha_nac,num_celular,genero,email,lugar_nacimiento,personas_dependientes,profecion,direccion,provincia,ciudad,parroquia,sector,referencia,telefono,tipo_casa,tiempo_residencia,propietario) 
values (2,'0702456358','Patricia', 'Tacuri', '1975-01-04', '0935955499', 'F', 'pa@hotmail.com', 'Tarqui', 'No', 'Desarrollador', 'A. Americas', 'Loja', 'Loja', 'Santiago', 'Parque central', 'Frente ala parque', '056789012', 'Arrendada', '15 años', 'Bryan Salazar',);
insert into socios(id,cedula,nombre,apellido,fecha_nac,num_celular,genero,email,lugar_nacimiento,personas_dependientes,profecion,direccion,provincia,ciudad,parroquia,sector,referencia,telefono,tipo_casa,tiempo_residencia,propietario) 
values (3,'6846654655','Luis', 'Villa', '1976-01-04', '0955997846', 'M', 'villa@hotmail.com', 'Loja', 'Si', 'Ingeniero', 'AV. Pumapungo ', 'Pichincha', 'Quito', 'La Magdalena', 'Valles', 'frente a la iglecia', '023456789', 'Cedida', '2 años', 'Santiago Dominguez',);
insert into socios(id,cedula,nombre,apellido,fecha_nac,num_celular,genero,email,lugar_nacimiento,personas_dependientes,profecion,direccion,provincia,ciudad,parroquia,sector,referencia,telefono,tipo_casa,tiempo_residencia,propietario) 
values (4,'0105068945','Tomas', 'Erazo', '1964-01-04', '0983742239', 'M', 'tomas@hotmail.com', 'Guayaquil', 'No', 'Arquitecto', 'S. Cordova 22', 'Tunguragua', 'Ambato', 'Pasa', 'Rio Patate', 'Tras el trerminal', '034567890', 'Propia', '6 años', 'Tomaz Erazo',);
insert into socios(id,cedula,nombre,apellido,fecha_nac,num_celular,genero,email,lugar_nacimiento,personas_dependientes,profecion,direccion,provincia,ciudad,parroquia,sector,referencia,telefono,tipo_casa,tiempo_residencia,propietario) 
values (5,'6846882445','Daniela', 'Rosero', '1992-01-04', '0973847422', 'F', 'danny@hotmail.com', 'Quito', 'Si', 'Enfermera', 'La Calle', 'El Oro', 'Machala', 'El Cambio', 'NOSE', 'salia de la ciudad', '067890123', 'Arrendada', '25 años', 'Derek Vergara',);